package ca.bc.gov.nrs.fsp.api.dao.v1;

import ca.bc.gov.nrs.fsp.api.dao.v1.bean.OrgUnitArrayElement;
import org.springframework.lang.Nullable;

import java.util.List;

/**
 * Wraps Oracle package FSP_700_WORKFLOW (legacy: pkgdefinitions/Fsp700Workflow.java).
 * 70 INOUT parameters. P_FSP_ORG_UNITS (#5) is a VARRAY of THE.FSP_ORG_UNIT_OBJECT.
 * Note legacy parameter #68 is "p_UPDATE_USERID" (lowercase 'p') — Oracle is case-insensitive
 * for unquoted identifiers, but we use the exact procedure descriptor positionally.
 */
public interface Fsp700WorkflowDao {

  String PACKAGE_NAME = "FSP_700_WORKFLOW";
  String PROCEDURE_NAME = "MAINLINE";

  record Result(
      String pAction,
      String pNewFspId,
      String pFspId,
      String pFspPlanName,
      List<OrgUnitArrayElement> pFspOrgUnits,
      String pFspStatusCode,
      String pFspStatusDesc,
      String pFspAmendmentCode,
      String pFspAmendmentDesc,
      String pNewFspAmendmentNumber,
      String pFspAmendmentNumber,
      String pUserClientNumber,
      String pUserRole,
      String pSubmissionId,
      String pFspExpiryDate,
      String pAmendmentName,
      String pAmendmentEfftvDate,
      String pFnrCompletedInd,
      String pFnrItemDescription,
      String pFnrEntryUserId,
      String pFnrEntryTimestamp,
      String pFnrComment,
      String pRsCompletedInd,
      String pRsItemDescription,
      String pRsEntryUserId,
      String pRsEntryTimestamp,
      String pRsComment,
      String pOrsCompletedInd,
      String pOrsItemDescription,
      String pOrsEntryUserId,
      String pOrsEntryTimestamp,
      String pOrsComment,
      String pDdmCompletedInd,
      String pDdmItemDescription,
      String pDdmEntryUserId,
      String pDdmEntryTimestamp,
      String pDdmComment,
      String pOtherCompletedInd,
      String pOtherItemDescription,
      String pOtherEntryUserId,
      String pOtherEntryTimestamp,
      String pOtherComment,
      String pEnableExtension,
      String pOtbhOfferedDate,
      String pOtbhOfferedComment,
      String pOtbhHeardDate,
      String pOtbhHeardComment,
      String pDdmOnlyStatusCode,
      String pDdmOnlyName,
      String pDdmOnlyDecisionDate,
      String pDdmOnlyComment,
      String pDdmOnlySubmissionDate,
      String pDdmOnlyEffectiveDate,
      String pExtensionStatusCode,
      String pExtensionId,
      String pExtensionName,
      String pExtensionDecisionDate,
      String pExtensionComment,
      String pExtensionSubmissionDate,
      String pExtensionEffectiveDate,
      String pFspReviewMilestoneTypCd,
      String pCompletedInd,
      String pOtbhDate,
      String pPlanStartDate,
      String pSubmissionDate,
      String pDecisionDate,
      String pReviewComment,
      String pUpdateUserid,
      String pErrorMessage,
      String pExtensionIds
  ) {}

  Result mainline(
      String pAction,
      String pNewFspId,
      String pFspId,
      String pFspPlanName,
      @Nullable List<OrgUnitArrayElement> pFspOrgUnits,
      String pFspStatusCode,
      String pFspStatusDesc,
      String pFspAmendmentCode,
      String pFspAmendmentDesc,
      String pNewFspAmendmentNumber,
      String pFspAmendmentNumber,
      String pUserClientNumber,
      String pUserRole,
      String pSubmissionId,
      String pFspExpiryDate,
      String pAmendmentName,
      String pAmendmentEfftvDate,
      String pFnrCompletedInd,
      String pFnrItemDescription,
      String pFnrEntryUserId,
      String pFnrEntryTimestamp,
      String pFnrComment,
      String pRsCompletedInd,
      String pRsItemDescription,
      String pRsEntryUserId,
      String pRsEntryTimestamp,
      String pRsComment,
      String pOrsCompletedInd,
      String pOrsItemDescription,
      String pOrsEntryUserId,
      String pOrsEntryTimestamp,
      String pOrsComment,
      String pDdmCompletedInd,
      String pDdmItemDescription,
      String pDdmEntryUserId,
      String pDdmEntryTimestamp,
      String pDdmComment,
      String pOtherCompletedInd,
      String pOtherItemDescription,
      String pOtherEntryUserId,
      String pOtherEntryTimestamp,
      String pOtherComment,
      String pEnableExtension,
      String pOtbhOfferedDate,
      String pOtbhOfferedComment,
      String pOtbhHeardDate,
      String pOtbhHeardComment,
      String pDdmOnlyStatusCode,
      String pDdmOnlyName,
      String pDdmOnlyDecisionDate,
      String pDdmOnlyComment,
      String pDdmOnlySubmissionDate,
      String pDdmOnlyEffectiveDate,
      String pExtensionStatusCode,
      String pExtensionId,
      String pExtensionName,
      String pExtensionDecisionDate,
      String pExtensionComment,
      String pExtensionSubmissionDate,
      String pExtensionEffectiveDate,
      String pFspReviewMilestoneTypCd,
      String pCompletedInd,
      String pOtbhDate,
      String pPlanStartDate,
      String pSubmissionDate,
      String pDecisionDate,
      String pReviewComment,
      String pUpdateUserid,
      String pExtensionIds
  );
}
